import type { Answers } from "./types";

/** Réponses DELIFOOD telles que le formulaire les produirait (doit donner le même snapshot que la fixture du moteur). */
export const delifoodAnswers: Answers = {
  "company.name": "DELIFOOD",
  "company.sector": "agroalimentaire",
  "company.city": "Douala, Cameroun",
  "company.contactName": "Direction",
  "production.product": "Sachets d'eau",
  "production.unit": "sachet",
  "production.ratePerHour": 3000,
  "production.marginPerUnit": 100,
  "production.hoursPerDay": 24,
  "production.daysPerYear": 365,
  "production.hasExtension": true,
  "production.targetRatePerHour": 6000,
  "production.targetDate": "T1 2027",
  "electricity.monthlyAverage": 6_227_916,
  "electricity.monthsObserved": 6,
  "electricity.wantsDetail": false,
  "electricity.hasPowerPenalty": true,
  "electricity.powerPenaltyMonthly": 353_665,
  "generator.has": true,
  "generator.fuelMode": "liters",
  "generator.litersPerMonth": 1500,
  "generator.pricePerLiter": 804,
  "generator.maintenancePerYear": 1_104_000,
  "outages.frequency": { count: 1, per: "day" },
  "outages.durationMin": 20,
  "outages.stoppedSharePct": 100,
  "outages.catchUpPct": 0,
  "hidden.hasIdleStaff": true,
  "hidden.headcount": 13,
  "hidden.hourlyCost": 500,
  "hidden.nonRedeployedPct": 100,
  "hidden.hasMaterialLoss": false,
  "hidden.hasCustomerPenalty": false,
  "project.goals": ["secure-production", "reduce-bill"],
  "project.horizonYears": 10,
  "contact.email": "direction@delifood.example",
};
