import { when } from "./conditions";
import type { FormDefinition } from "./types";

export const SECTORS = [
  { value: "agroalimentaire", label: "Agroalimentaire" },
  { value: "boissons", label: "Boissons et eau" },
  { value: "plastique", label: "Plasturgie et emballage" },
  { value: "textile", label: "Textile" },
  { value: "chimie", label: "Chimie et cosmétique" },
  { value: "metallurgie", label: "Métallurgie et mécanique" },
  { value: "bois", label: "Bois et ameublement" },
  { value: "pharma", label: "Pharmaceutique" },
  { value: "autre", label: "Autre" },
] as const;

export const PRODUCTION_UNITS = [
  { value: "sachet", label: "Sachet" },
  { value: "bouteille", label: "Bouteille" },
  { value: "kg", label: "Kilogramme" },
  { value: "tonne", label: "Tonne" },
  { value: "pièce", label: "Pièce" },
  { value: "litre", label: "Litre" },
  { value: "carton", label: "Carton" },
] as const;

export const GOALS = [
  { value: "reduce-bill", label: "Réduire ma facture d'électricité" },
  { value: "secure-production", label: "Sécuriser ma production contre les coupures" },
  { value: "autonomy", label: "Gagner en autonomie énergétique" },
  { value: "growth", label: "Accompagner une extension de capacité" },
  { value: "image", label: "Réduire mon empreinte carbone" },
] as const;

/**
 * Définition du formulaire de diagnostic (v1).
 * Ordre = ordre d'affichage. Les ids sont les clés plates des réponses.
 */
export const formDefinition: FormDefinition = {
  version: 1,
  sections: [
    {
      id: "company",
      title: "Votre entreprise",
      intro: "Commençons par faire connaissance.",
      questions: [
        {
          id: "company.name",
          type: "text",
          title: "Quel est le nom de votre entreprise ?",
          placeholder: "Ex. : DELIFOOD",
          maxLength: 80,
        },
        {
          id: "company.sector",
          type: "select",
          title: "Dans quel secteur opérez-vous ?",
          options: SECTORS,
        },
        {
          id: "company.city",
          type: "text",
          title: "Où se situe votre site de production ?",
          description: "Ville et pays.",
          placeholder: "Ex. : Douala, Cameroun",
          maxLength: 80,
        },
        {
          id: "company.contactName",
          type: "text",
          title: "Qui est notre interlocuteur ?",
          description: "Nom et fonction, pour personnaliser le rapport.",
          required: false,
          maxLength: 80,
        },
      ],
    },
    {
      id: "production",
      title: "Votre production",
      intro:
        "Quelques repères sur ce que vous produisez : ils servent à chiffrer ce que coûte chaque arrêt.",
      questions: [
        {
          id: "production.product",
          type: "text",
          title: "Que produisez-vous principalement ?",
          placeholder: "Ex. : sachets d'eau",
          maxLength: 80,
        },
        {
          id: "production.unit",
          type: "select",
          title: "Dans quelle unité comptez-vous votre production ?",
          options: PRODUCTION_UNITS,
          allowCustom: true,
        },
        {
          id: "production.ratePerHour",
          type: "number",
          title: "Combien d'unités produisez-vous par heure ?",
          description: "Cadence habituelle, en fonctionnement normal.",
          unit: "unités / heure",
          min: 1,
        },
        {
          id: "production.marginPerUnit",
          type: "currency",
          title: "Quelle marge dégagez-vous par unité produite ?",
          description:
            "Marge contributive (prix de vente moins coûts variables), pas le prix de vente. En cas de doute, prenez une valeur prudente.",
          per: "/ unité",
          min: 1,
        },
        {
          id: "production.hoursPerDay",
          type: "number",
          title: "Combien d'heures produisez-vous par jour ?",
          unit: "h / jour",
          min: 1,
          max: 24,
        },
        {
          id: "production.daysPerYear",
          type: "number",
          title: "Combien de jours produisez-vous par an ?",
          unit: "jours / an",
          min: 1,
          max: 366,
          integer: true,
        },
        {
          id: "production.hasExtension",
          type: "yesno",
          title: "Prévoyez-vous d'augmenter votre capacité ?",
        },
        {
          id: "production.targetRatePerHour",
          type: "number",
          title: "Quelle sera votre cadence cible ?",
          unit: "unités / heure",
          min: 1,
          showIf: when.yes("production.hasExtension"),
        },
        {
          id: "production.targetDate",
          type: "text",
          title: "À quelle échéance ?",
          placeholder: "Ex. : T1 2027",
          required: false,
          maxLength: 40,
          showIf: when.yes("production.hasExtension"),
        },
      ],
    },
    {
      id: "electricity",
      title: "Votre électricité réseau",
      intro: "Ce que vous payez déjà au fournisseur d'électricité.",
      questions: [
        {
          id: "electricity.monthlyAverage",
          type: "currency",
          title: "Quel est le montant moyen de votre facture d'électricité ?",
          description: "Montant mensuel TTC, tel qu'il apparaît sur la facture.",
          per: "/ mois",
          min: 1,
        },
        {
          id: "electricity.monthsObserved",
          type: "number",
          title: "Sur combien de mois avez-vous calculé cette moyenne ?",
          description: "12 mois consécutifs donnent le résultat le plus fiable.",
          unit: "mois",
          min: 1,
          max: 12,
          integer: true,
        },
        {
          id: "electricity.wantsDetail",
          type: "yesno",
          title: "Souhaitez-vous saisir vos factures mois par mois ?",
          description: "Facultatif : plus précis si vous les avez sous la main.",
        },
        {
          id: "electricity.months",
          type: "monthTable",
          title: "Vos 12 dernières factures",
          description: "Laissez vide les mois que vous n'avez pas.",
          showIf: when.yes("electricity.wantsDetail"),
        },
        {
          id: "electricity.hasPowerPenalty",
          type: "yesno",
          title: "Votre facture comporte-t-elle une pénalité de dépassement de puissance ?",
          description:
            "Ligne « dépassement », « pénalité » ou « puissance appelée » sur la facture.",
        },
        {
          id: "electricity.powerPenaltyMonthly",
          type: "currency",
          title: "Quel est le montant mensuel moyen de cette pénalité ?",
          per: "/ mois",
          min: 1,
          showIf: when.yes("electricity.hasPowerPenalty"),
        },
      ],
    },
    {
      id: "generator",
      title: "Votre groupe électrogène",
      questions: [
        { id: "generator.has", type: "yesno", title: "Disposez-vous d'un groupe électrogène ?" },
        {
          id: "generator.fuelMode",
          type: "choice",
          title: "Comment suivez-vous votre consommation de carburant ?",
          options: [
            {
              value: "liters",
              label: "En litres",
              description: "Je connais les litres consommés et le prix du litre",
            },
            {
              value: "amount",
              label: "En montant",
              description: "Je connais ma dépense mensuelle en carburant",
            },
          ],
          showIf: when.yes("generator.has"),
        },
        {
          id: "generator.litersPerMonth",
          type: "number",
          title: "Combien de litres consommez-vous par mois ?",
          unit: "l / mois",
          min: 1,
          showIf: when.all(when.yes("generator.has"), when.equals("generator.fuelMode", "liters")),
        },
        {
          id: "generator.pricePerLiter",
          type: "currency",
          title: "Quel est le prix du litre ?",
          per: "/ litre",
          min: 1,
          showIf: when.all(when.yes("generator.has"), when.equals("generator.fuelMode", "liters")),
        },
        {
          id: "generator.amountPerMonth",
          type: "currency",
          title: "Combien dépensez-vous en carburant par mois ?",
          per: "/ mois",
          min: 1,
          showIf: when.all(when.yes("generator.has"), when.equals("generator.fuelMode", "amount")),
        },
        {
          id: "generator.maintenancePerYear",
          type: "currency",
          title: "Combien vous coûte l'entretien du groupe par an ?",
          description: "Vidanges, filtres, réparations, contrat de maintenance.",
          per: "/ an",
          min: 0,
          showIf: when.yes("generator.has"),
        },
      ],
    },
    {
      id: "outages",
      title: "Les coupures",
      intro: "Décrivons l'instabilité du réseau telle que vous la vivez.",
      questions: [
        {
          id: "outages.frequency",
          type: "frequency",
          title: "À quelle fréquence subissez-vous des coupures ?",
          description: "Une estimation honnête suffit.",
        },
        {
          id: "outages.durationMin",
          type: "number",
          title: "Combien de temps dure une coupure en moyenne ?",
          description: "Jusqu'à la reprise effective de la production.",
          unit: "minutes",
          min: 1,
        },
        {
          id: "outages.stoppedSharePct",
          type: "number",
          title: "Quelle part de votre production s'arrête pendant une coupure ?",
          description: "100 % si tout s'arrête.",
          unit: "%",
          min: 1,
          max: 100,
        },
        {
          id: "outages.catchUpPct",
          type: "number",
          title: "Quelle part de la production perdue rattrapez-vous plus tard ?",
          description: "0 % si le temps perdu est définitivement perdu.",
          unit: "%",
          min: 0,
          max: 100,
        },
      ],
    },
    {
      id: "hidden",
      title: "Les coûts cachés",
      intro: "Ce que les coupures vous coûtent au-delà de la production.",
      questions: [
        {
          id: "hidden.hasIdleStaff",
          type: "yesno",
          title: "Pendant une coupure, des salariés restent-ils sans tâche ?",
        },
        {
          id: "hidden.headcount",
          type: "number",
          title: "Combien de personnes sont concernées ?",
          unit: "personnes",
          min: 1,
          integer: true,
          showIf: when.yes("hidden.hasIdleStaff"),
        },
        {
          id: "hidden.hourlyCost",
          type: "currency",
          title: "Quel est leur coût horaire moyen chargé ?",
          per: "/ heure",
          min: 1,
          showIf: when.yes("hidden.hasIdleStaff"),
        },
        {
          id: "hidden.nonRedeployedPct",
          type: "number",
          title: "Quelle part de ce temps n'est pas réaffectée à une autre tâche ?",
          description: "100 % si personne n'est redéployé.",
          unit: "%",
          min: 1,
          max: 100,
          showIf: when.yes("hidden.hasIdleStaff"),
        },
        {
          id: "hidden.hasMaterialLoss",
          type: "yesno",
          title: "Une coupure entraîne-t-elle de la matière perdue ou du rebut ?",
        },
        {
          id: "hidden.quantityPerOutage",
          type: "number",
          title: "Quelle quantité est perdue à chaque coupure ?",
          description: "Dans l'unité qui vous parle (kg, litres, lots…).",
          unit: "unités",
          min: 0.01,
          showIf: when.yes("hidden.hasMaterialLoss"),
        },
        {
          id: "hidden.unitCost",
          type: "currency",
          title: "Quel est le coût de cette unité perdue ?",
          per: "/ unité",
          min: 1,
          showIf: when.yes("hidden.hasMaterialLoss"),
        },
        {
          id: "hidden.nonRecoverablePct",
          type: "number",
          title: "Quelle part n'est pas récupérable ?",
          unit: "%",
          min: 1,
          max: 100,
          showIf: when.yes("hidden.hasMaterialLoss"),
        },
        {
          id: "hidden.hasCustomerPenalty",
          type: "yesno",
          title:
            "Les retards liés aux coupures vous ont-ils déjà coûté des pénalités ou des commandes ?",
        },
        {
          id: "hidden.customerPenaltyPerYear",
          type: "currency",
          title: "À combien estimez-vous ces pertes sur un an ?",
          description: "Uniquement les pertes certaines (pénalités payées, commandes annulées).",
          per: "/ an",
          min: 1,
          showIf: when.yes("hidden.hasCustomerPenalty"),
        },
      ],
    },
    {
      id: "project",
      title: "Votre projet",
      questions: [
        {
          id: "project.goals",
          type: "multichoice",
          title: "Qu'attendez-vous d'abord d'une solution énergétique ?",
          description: "Plusieurs réponses possibles.",
          options: GOALS,
        },
        {
          id: "project.horizonYears",
          type: "number",
          title: "Sur combien d'années souhaitez-vous comparer les scénarios ?",
          unit: "ans",
          min: 5,
          max: 20,
          integer: true,
        },
      ],
    },
    {
      id: "final",
      title: "Votre rapport",
      questions: [
        {
          id: "final.summary",
          type: "summary",
          title: "Voici ce que nous avons compris",
          description: "Vérifiez les montants annualisés avant de générer votre rapport.",
        },
        {
          id: "contact.email",
          type: "email",
          title: "À quelle adresse devons-nous envoyer votre rapport ?",
        },
      ],
    },
  ],
};
